# Generated by Django 4.2.6 on 2023-10-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_taskPro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefas',
            new_name='Tarefa',
        ),
    ]
