# Generated by Django 4.2.6 on 2023-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taskPro', '0002_rename_tarefas_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='idade',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tarefa',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
